/**
 * Rasterise Natural Earth land polygons into a packed bitmask.
 *
 * The swarm needs to know "is this grid cell land?" for every seat it places,
 * on the server (for the SVG fallback) and in the browser (for the canvas).
 * Shipping TopoJSON to do that at runtime would cost ~100 kB and a polygon
 * library; a packed bitmask costs a few kB and one array lookup.
 *
 * Run:  pnpm tsx scripts/generate-landmask.ts
 * Out:  data/landmask.json
 *
 * The TopoJSON dependency is dev-only. Nothing in this file ships.
 */
import { writeFileSync } from "node:fs";
import { gzipSync } from "node:zlib";
import { geoContains } from "d3-geo";
import * as topojson from "topojson-client";
import land110m from "world-atlas/land-110m.json" with { type: "json" };

/** Degrees per cell. 0.5 keeps Japan and the Korean peninsula readable when
 *  the mobile viewport zooms into Asia-Pacific. */
const STEP = 0.5;

/** Antarctica is dropped: it adds a heavy white band and no information. */
const LAT_MIN = -58;
const LAT_MAX = 78;
const LON_MIN = -180;
const LON_MAX = 180;

const cols = Math.round((LON_MAX - LON_MIN) / STEP);
const rows = Math.round((LAT_MAX - LAT_MIN) / STEP);

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const topology = land110m as any;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const landFeature = topojson.feature(topology, topology.objects.land) as any;

console.log(`grid ${cols} x ${rows} = ${cols * rows} cells @ ${STEP}deg`);

const bytes = new Uint8Array(Math.ceil((cols * rows) / 8));
let landCells = 0;
const started = Date.now();

for (let row = 0; row < rows; row++) {
  // Row 0 is the top of the image, which is the *highest* latitude.
  const lat = LAT_MAX - (row + 0.5) * STEP;
  for (let col = 0; col < cols; col++) {
    const lon = LON_MIN + (col + 0.5) * STEP;
    if (!geoContains(landFeature, [lon, lat])) continue;
    const bit = row * cols + col;
    bytes[bit >> 3]! |= 0b1000_0000 >> (bit & 7);
    landCells++;
  }
  if (row % 40 === 0) process.stdout.write(".");
}
process.stdout.write("\n");

const base64 = Buffer.from(bytes).toString("base64");
const out = {
  $comment:
    "Generated by scripts/generate-landmask.ts from world-atlas land-110m (Natural Earth). Row 0 is the northernmost row. Bit order is MSB-first within each byte.",
  step: STEP,
  cols,
  rows,
  bounds: { latMin: LAT_MIN, latMax: LAT_MAX, lonMin: LON_MIN, lonMax: LON_MAX },
  landCells,
  bits: base64,
};

writeFileSync("data/landmask.json", `${JSON.stringify(out)}\n`);

const raw = Buffer.byteLength(JSON.stringify(out));
const gz = gzipSync(Buffer.from(JSON.stringify(out))).byteLength;
console.log(
  `land cells ${landCells} (${((landCells / (cols * rows)) * 100).toFixed(1)}%) ` +
    `· ${(Date.now() - started) / 1000}s\n` +
    `raw ${(raw / 1024).toFixed(1)} kB · gzip ${(gz / 1024).toFixed(1)} kB`,
);
